// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Navbar items', function() {
    var element, scope;
    scope = null;
    element = null;
    beforeEach(module('btDirectives'));
    beforeEach(inject(function(_$rootScope_, _$compile_) {
      element = angular.element('<div><bt-page-nav></bt-page-nav></div>');
      scope = _$rootScope_;
      _$compile_(element)(scope);
      return scope.$digest();
    }));
    it('should have a single root', function() {
      return expect(element.find('ul.navbar-nav').length).toEqual(1);
    });
    it('should create a navbar list', function() {
      var navItems;
      navItems = element.find('ul.navbar-nav li');
      return expect(navItems.length).toBeGreaterThan(0);
    });
    return describe('#isPage', function() {
      var location;
      location = null;
      beforeEach(inject(function(_$location_) {
        location = _$location_;
        return location.path('/bills');
      }));
      it('should return true if passed the current page name (bills)', function() {
        return expect(scope.isPage('bills')).toBe(true);
      });
      it('should return true if the passed name is the root of the current path (bills for /bills/1)', function() {
        location.path('/bills/201');
        return expect(scope.isPage('bills')).toBe(true);
      });
      it('should return false if passed the wrong name (notbills)', function() {
        return expect(scope.isPage('notbills')).toBe(false);
      });
      it('should return false if passed "root"', function() {
        return expect(scope.isPage('root')).toBe(false);
      });
      return describe('on the root path /', function() {
        beforeEach(function() {
          return location.path('/');
        });
        it('should return true if passed "root"', function() {
          return expect(scope.isPage('root')).toBe(true);
        });
        return it('should return false if passed anything else', function() {
          return expect(scope.isPage('bills')).toBe(false);
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=btPageNavSpec.map
*/
