// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Bill Controller: Index (BillIndexCtrl)', function() {
    var scope;
    scope = null;
    beforeEach(module('btControllers'));
    beforeEach(inject(function(_$controller_, _$rootScope_) {
      var BillIndexCtrl;
      scope = _$rootScope_;
      return BillIndexCtrl = _$controller_('BillIndexCtrl', {
        $scope: scope
      });
    }));
    return describe('GET bills#all', function() {
      var mockBills;
      mockBills = null;
      beforeEach(inject(function(_$httpBackend_) {
        var hostUrl, httpBackend;
        httpBackend = _$httpBackend_;
        hostUrl = 'https://api.troycitytracker.com';
        mockBills = '[{"id":9,"legislation_type":"Resolution","title":"Bond Resolution of the City ofTroy, New York Authorizing the Issuance of$3,537,411 in Serial Bonds to Finance a Capital Project Described in the Combined Sewer Overflow Long Term Control Plan. (Council President Wiltshire) (At the Request ofthe Administration)","short_title":"Issue bonds to fund Sewer Overflow Plan","url":"http://api.troycitytracker.com/v1/bills/9","pdf":"http://api.troycitytracker.com/bills/9.pdf"}]';
        httpBackend.expectGET(hostUrl + '/bills').respond(200, mockBills);
        return httpBackend.flush();
      }));
      return it('returns a list of bills', function() {
        return expect(scope.bills).toEqual(JSON.parse(mockBills));
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=billIndexCtrlSpec.map
*/
