// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Bill Controller: Index (BillIndexCtrl)', function() {
    var scope;
    scope = null;
    beforeEach(module('btControllers'));
    beforeEach(inject(function(_$controller_, _$rootScope_) {
      var BillIndexCtrl;
      scope = _$rootScope_;
      return BillIndexCtrl = _$controller_('BillIndexCtrl', {
        $scope: scope
      });
    }));
    return describe('GET bills#all', function() {
      var mockBills;
      mockBills = null;
      beforeEach(inject(function(_$httpBackend_) {
        var hostUrl, httpBackend;
        httpBackend = _$httpBackend_;
        hostUrl = 'https://api.troycitytracker.com';
        mockBills = '[{"id":1,"name":"Finance Committee Meeting on May 7th, 2015 18:00","date":"2015-05-07T18:00:00.000-04:00","location":"Suite 5, 433 River Street, Troy, NY 12180","bill_count":6,"organization":{"id":3,"name":"Finance Committee","url":"http://api.troycitytracker.com/v1/organizations/3"},"agenda":{"approved":false,"pdf":"http://api.troycitytracker.com/meetings/1/agenda.pdf"},"minutes":{"approved":false,"pdf":"http://api.troycitytracker.com/meetings/1/minutes.pdf"},"url":"http://api.troycitytracker.com/v1/meetings/1"},{"id":3,"name":"Technology Committee Meeting on May 21st, 2015 15:00","date":"2015-05-21T15:00:00.000-04:00","location":"Suite 5, 433 River Street, Troy, NY 12180","bill_count":3,"organization":{"id":12,"name":"Technology Committee","url":"http://api.troycitytracker.com/v1/organizations/12"},"agenda":{"approved":false,"pdf":"http://api.troycitytracker.com/meetings/3/agenda.pdf"},"minutes":{"approved":false,"pdf":"http://api.troycitytracker.com/meetings/3/minutes.pdf"},"url":"http://api.troycitytracker.com/v1/meetings/3"}]';
        httpBackend.expectGET(hostUrl + '/bills').respond(200, mockBills);
        return httpBackend.flush();
      }));
      return it('returns a list of bills', function() {
        return expect(scope.bills).toEqual(JSON.parse(mockBills));
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=meetingIndexCtrlSpec.map
*/
