// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Person Controller: Show (PersonShowCtrl)', function() {
    var scope;
    scope = null;
    beforeEach(module('btControllers'));
    beforeEach(inject(function(_$controller_, _$rootScope_) {
      var PersonShowCtrl;
      scope = _$rootScope_;
      return PersonShowCtrl = _$controller_('PersonShowCtrl', {
        $scope: scope,
        $routeParams: {
          id: 1
        }
      });
    }));
    return describe('GET people#show', function() {
      var mockPerson;
      mockPerson = null;
      beforeEach(inject(function(_$httpBackend_) {
        var hostUrl, httpBackend;
        httpBackend = _$httpBackend_;
        hostUrl = 'https://api.troycitytracker.com';
        mockPerson = '{"id":1,"first":"Rodney","last":"Wiltshire, Jr.","bio":"City Council President, At large city council member, Chair of the Finance Committee.","created_at":"2015-05-01T10:44:04.914-04:00","updated_at":"2015-05-01T11:16:16.565-04:00","memberships":[{"id":2,"name":"City Council"},{"id":3,"name":"Finance Committee"}],"sponsorships":[],"people_url":"http://api.troycitytracker.com/v1/people"}';
        httpBackend.expectGET(hostUrl + '/people/1').respond(200, mockPerson);
        return httpBackend.flush();
      }));
      return it('returns a list of people', function() {
        return expect(scope.person).toEqual(JSON.parse(mockPerson));
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=personShowCtrlSpec.map
*/
