// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Person Controller: Index (PersonIndexCtrl)', function() {
    var scope;
    scope = null;
    beforeEach(module('btControllers'));
    beforeEach(inject(function(_$controller_, _$rootScope_) {
      var PersonIndexCtrl;
      scope = _$rootScope_;
      return PersonIndexCtrl = _$controller_('PersonIndexCtrl', {
        $scope: scope
      });
    }));
    return describe('GET people#all', function() {
      var mockPeople;
      mockPeople = null;
      beforeEach(inject(function(_$httpBackend_) {
        var hostUrl, httpBackend;
        httpBackend = _$httpBackend_;
        hostUrl = 'https://api.troycitytracker.com';
        mockPeople = '[{"id":3,"first":"Rodney","last":"Wiltshire, Jr.","url":"http://api.troycitytracker.com/v1/people/3"},{"id":5,"first":"Lynn M. ","last":"Kopka","url":"http://api.troycitytracker.com/v1/people/5"},{"id":4,"first":"Erin ","last":"Sullivan-Teta","url":"http://api.troycitytracker.com/v1/people/4"},{"id":6,"first":"James","last":"Gordon","url":"http://api.troycitytracker.com/v1/people/6"},{"id":7,"first":"Anastasia","last":"Robertson","url":"http://api.troycitytracker.com/v1/people/7"},{"id":8,"first":"Dean","last":"Bodnar","url":"http://api.troycitytracker.com/v1/people/8"},{"id":9,"first":"Robert J.","last":"Doherty","url":"http://api.troycitytracker.com/v1/people/9"},{"id":10,"first":"Ken","last":"Zalewski","url":"http://api.troycitytracker.com/v1/people/10"},{"id":11,"first":"Gary","last":"Galuski","url":"http://api.troycitytracker.com/v1/people/11"}]';
        httpBackend.expectGET(hostUrl + '/people').respond(200, mockPeople);
        return httpBackend.flush();
      }));
      return it('returns a list of bills', function() {
        return expect(scope.people).toEqual(JSON.parse(mockPeople));
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=personIndexCtrlSpec.map
*/
