// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Route configuration', function() {
    var route;
    route = null;
    beforeEach(module('billTrackerApp'));
    beforeEach(inject(function(_$route_) {
      return route = _$route_;
    }));
    describe('non-namespaced resources', function() {
      return describe('GET /', function() {
        it('should use MainCtrl', function() {
          return expect(route.routes['/'].controller).toBe('MainCtrl');
        });
        return it('should render from views/main.html', function() {
          return expect(route.routes['/'].templateUrl).toBe('views/main.html');
        });
      });
    });
    describe('Bill resources', function() {
      describe('GET /bills', function() {
        it('should use BillIndexCtrl', function() {
          return expect(route.routes['/bills'].controller).toBe('BillIndexCtrl');
        });
        return it('should render from views/bills/index.html', function() {
          return expect(route.routes['/bills'].templateUrl).toBe('views/bills/index.html');
        });
      });
      return describe('GET /bills/:id', function() {
        it('should use BillShowCtrl', function() {
          return expect(route.routes['/bills/:id'].controller).toBe('BillShowCtrl');
        });
        return it('should render from views/bills/show.html', function() {
          return expect(route.routes['/bills/:id'].templateUrl).toBe('views/bills/show.html');
        });
      });
    });
    describe('People resources', function() {
      describe('GET /people', function() {
        it('should use PersonIndexCtrl', function() {
          return expect(route.routes['/people'].controller).toBe('PersonIndexCtrl');
        });
        return it('should render from views/people/index.html', function() {
          return expect(route.routes['/people'].templateUrl).toBe('views/people/index.html');
        });
      });
      return describe('GET /people/:id', function() {
        it('should use PersonShowCtrl', function() {
          return expect(route.routes['/people/:id'].controller).toBe('PersonShowCtrl');
        });
        return it('should render from views/people/show.html', function() {
          return expect(route.routes['/people/:id'].templateUrl).toBe('views/people/show.html');
        });
      });
    });
    describe('Committees resources', function() {
      describe('GET /committees', function() {
        it('should use CommitteeIndexCtrl', function() {
          return expect(route.routes['/committees'].controller).toBe('CommitteeIndexCtrl');
        });
        return it('should render from views/committees/index.html', function() {
          return expect(route.routes['/committees'].templateUrl).toBe('views/committees/index.html');
        });
      });
      return describe('GET /committees/:id', function() {
        it('should use CommitteeShowCtrl', function() {
          return expect(route.routes['/committees/:id'].controller).toBe('CommitteeShowCtrl');
        });
        return it('should render from views/committees/show.html', function() {
          return expect(route.routes['/committees/:id'].templateUrl).toBe('views/committees/show.html');
        });
      });
    });
    return describe('meetings resources', function() {
      describe('GET /meetings', function() {
        it('should use MeetingIndexCtrl', function() {
          return expect(route.routes['/meetings'].controller).toBe('MeetingIndexCtrl');
        });
        return it('should render from views/meetings/index.html', function() {
          return expect(route.routes['/meetings'].templateUrl).toBe('views/meetings/index.html');
        });
      });
      return describe('GET /meetings/:id', function() {
        it('should use MeetingShowCtrl', function() {
          return expect(route.routes['/meetings/:id'].controller).toBe('MeetingShowCtrl');
        });
        return it('should render from views/meetings/show.html', function() {
          return expect(route.routes['/meetings/:id'].templateUrl).toBe('views/meetings/show.html');
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=routesSpec.map
*/
